// <auto-generated />
namespace FsEfTest.Migrations

open System
open FsEfTest
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion

[<DbContext(typeof<BloggingModel.BloggingContext>)>]
type BloggingContextModelSnapshot() =
    inherit ModelSnapshot()

    override this.BuildModel(modelBuilder: ModelBuilder) =
        modelBuilder
            .HasAnnotation("ProductVersion", "6.0.13")
            .HasAnnotation("Relational:MaxIdentifierLength", 64) |> ignore

        modelBuilder.Entity("FsEfTest.BloggingModel+Blog", (fun b ->

            b.Property<int>("Id")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("int")
                |> ignore

            b.Property<string>("Url")
                .IsRequired(true)
                .HasColumnType("longtext")
                |> ignore

            b.HasKey("Id")
                |> ignore


            b.ToTable("Blogs") |> ignore

        )) |> ignore

